### ISSUE TITLE
Testbed with Ubuntu 17.10

### ISSUE THREAD

**Issue by pgr123** [pybox2d/pybox2d#100]
I use xubuntu 17.10 and I cannot run the tests in testbed, particularly test_Chain.py.
All worked fine in xubuntu 16.04 ; in xubuntu 17.04, I must reinstall the pybox2d from the 16.04 version but with the 17.10, I have no success ; I tried all the old versions and nothing works. So do you think the new version of pybox2d (and pygame) will work with ubunrtu 18.04 (and testbed) ?
Excuse my bad english.
Thank you.
pgr123

**Comment by raraizan** [comment]
I'm using ubuntu 18.04, python 3.6 y PyBox2D v2.3.2. Everything is working fine except for a warning from a deprecated warning while running test_join.py

**Comment by kne** [comment]
It should work on multiple platforms without issue. Closing until further details are included.
