### ISSUE TITLE
Conda install not working for python 3

### ISSUE THREAD

**Issue by michaelkhan3** [pybox2d/pybox2d#101]
When I try to install the package  using 

conda install -c kne pybox2d 

I get the following error suggesting that the package is only compatible with python 2.7

`UnsatisfiableError: The following specifications were found to be in conflict:
  - pybox2d -> python 2.7*
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.`

I'm using Windows 10  and Anaconda 4.3.30

**Comment by radusl** [comment]
I get the exact same error
`conda install -c kne pybox2d
Fetching package metadata ...............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - pybox2d -> python 2.7*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.`

**Comment by PoojaKatariya1811** [comment]
i have a similar error

 C:\Users\user>conda install -c kne pybox2d
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - pybox2d
  - tensorflow
Use "conda info <package>" to see the dependencies for each package.

i am using python 3.6 for this environment on windows 10

**Comment by PoojaKatariya1811** [comment]
Here's what I did,
First I created a new environment
then installed pybox2d by using conda: conda install -c kne pybox2d
Once this was completed I installed tensorflow package from anaconda navigator.
This solved the problem for me.

**Comment by kne** [comment]
`pybox2d` is now on conda-forge, easing distribution on multiple python versions + platforms. To install it from there, please use
`conda install -c conda-forge pybox2d`

The `kne` channel on conda-forge will be cleared out in the near future and will not be updated.
