### ISSUE TITLE
PyBox2d fail to build with MinGW on Windows

### ISSUE THREAD

**Issue by Amathlog** [pybox2d/pybox2d#105]
Hi,
I've just run into an issue when installing PyBox2D on my Windows machine.
For some reason, the installation was using the gcc compiler in MinGW (version 7.3.0) and it failed to build. When I forced to use msvc, it worked.

The main error is with the definition of some hash function.
Like:
```
Box2D\Box2D_wrap.cpp: In function 'long int b2DrawExtended___hash__(b2DrawExtended*)':
    Box2D\Box2D_wrap.cpp:4933:77: error: cast from 'b2DrawExtended*' to 'long int' loses precision [-fpermissive]
     SWIGINTERN long b2DrawExtended___hash__(b2DrawExtended *self){ return (long)self; }
```
I dunno if I should report this on the main Box2D repo or here.
Thanks!

**Comment by bombhero** [comment]
I reproduced this issue.

**Comment by bombhero** [comment]
I find the solution today.
I guess the reason is the point 'b2DrawExtended*'(64bit in 64bit system) cannot be covered by 'long int'(32bit).
The solution is edit <python_path>\Lib\distutils\distutils.cfg and remove below configuration.

[build]           
compiler=mingw32

**Comment by bombhero** [comment]
Should use mingw-w64. I install it in conda
conda install m2w64-toolchain

**Comment by kne** [comment]
You reported this to the correct repo - thanks @Amathlog.

I believe this is now correctly handled in https://github.com/pybox2d/pybox2d/pull/117/commits/a56c47e42fa34707b430c9a6c06d1e4a73c95907, as it seems to be building on Linux/Windows/OSX according to CI.
