### ISSUE TITLE
Not able to install Box2D Python 3.6 Windows 10

### ISSUE THREAD

**Issue by sande12142** [pybox2d/pybox2d#106]
I have tried a number of approaches but still receive errors when trying to install Box2D on Windows.  My error looks as follows:

Requirement already satisfied: gym[box2d] in c:\users\ander\anaconda3\envs\drlnd\lib\site-packages (0.10.8)
Requirement already satisfied: requests>=2.0 in c:\users\ander\anaconda3\envs\drlnd\lib\site-packages (from gym[box2d]) (2.20.0)
Requirement already satisfied: scipy in c:\users\ander\anaconda3\envs\drlnd\lib\site-packages (from gym[box2d]) (1.1.0)
Requirement already satisfied: numpy>=1.10.4 in c:\users\ander\anaconda3\envs\drlnd\lib\site-packages (from gym[box2d]) (1.15.4)
Requirement already satisfied: six in c:\users\ander\anaconda3\envs\drlnd\lib\site-packages (from gym[box2d]) (1.11.0)
Requirement already satisfied: pyglet>=1.2.0 in c:\users\ander\anaconda3\envs\drlnd\lib\site-packages (from gym[box2d]) (1.3.2)
Collecting box2d-py>=2.3.5; extra == "box2d" (from gym[box2d])
  Using cached https://files.pythonhosted.org/packages/dd/5a/ad8d3ef9c13d5afcc1e44a77f11792ee717f6727b3320bddbc607e935e2a/box2d-py-2.3.5.tar.gz
Requirement already satisfied: idna<2.8,>=2.5 in c:\users\ander\anaconda3\envs\drlnd\lib\site-packages (from requests>=2.0->gym[box2d]) (2.7)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in c:\users\ander\anaconda3\envs\drlnd\lib\site-packages (from requests>=2.0->gym[box2d]) (1.24)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\ander\anaconda3\envs\drlnd\lib\site-packages (from requests>=2.0->gym[box2d]) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\ander\anaconda3\envs\drlnd\lib\site-packages (from requests>=2.0->gym[box2d]) (2018.10.15)
Requirement already satisfied: future in c:\users\ander\anaconda3\envs\drlnd\lib\site-packages (from pyglet>=1.2.0->gym[box2d]) (0.16.0)
Building wheels for collected packages: box2d-py
  Running setup.py bdist_wheel for box2d-py ... error
  Complete output from command C:\Users\ander\Anaconda3\envs\drlnd\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ander\\AppData\\Local\\Temp\\pip-install-7c98mzi0\\box2d-py\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\ander\AppData\Local\Temp\pip-wheel-gny37x57 --python-tag cp36:
  Using setuptools (version 40.5.0).
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\Box2D
  copying library\Box2D\Box2D.py -> build\lib.win-amd64-3.6\Box2D
  copying library\Box2D\__init__.py -> build\lib.win-amd64-3.6\Box2D
  creating build\lib.win-amd64-3.6\Box2D\b2
  copying library\Box2D\b2\__init__.py -> build\lib.win-amd64-3.6\Box2D\b2
  running build_ext
  building 'Box2D._Box2D' extension
  swigging Box2D\Box2D.i to Box2D\Box2D_wrap.cpp
  C:\Users\ander\Anaconda3\envs\drlnd\swig.exe -python -c++ -IBox2D -small -O -includeall -ignoremissing -w201 -globals b2Globals -outdir library\Box2D -keyword -w511 -D_SWIG_KWARGS -o Box2D\Box2D_wrap.cpp Box2D\Box2D.i
  C:\Users\ander\Anaconda3\envs\drlnd\Lib\pyprimtypes.swg(7) : Error: Syntax error in input(1).
  error: command 'C:\\Users\\ander\\Anaconda3\\envs\\drlnd\\swig.exe' failed with exit status 1

Any help is greatly appreciated.  I am trying to develop a project for a class but can't get my environment installed.  I am certain the project will take a fraction of the time this error has cost me.

Thank you,

Scott

**Comment by blmussati** [comment]
Does anyone know how to solve this? I have exactly the same issue.

**Comment by TheCoderMan2000** [comment]
Do you have visual studios for c++ installed? Maybe that is the issue.

**Comment by jcarcamo** [comment]
I followed the instructions provided at [Installing pocketsphinx python module: command 'swig.exe' failed](https://stackoverflow.com/questions/44504899/installing-pocketsphinx-python-module-command-swig-exe-failed) and it did the trick for me. 

Don't forget to install (Microsoft Build Tools 2015 Update 3)[https://visualstudio.microsoft.com/vs/older-downloads/]

**Comment by kemalaraz** [comment]
Go to C:\Users\UserName\Anaconda3\envs\gym\conda-meta and open swig file. Change the bold italic part from swig-3.0.12-h047fa9f_3.tar.bz2 to swig-3.0.12-h5a33001_3.tar.bz2 ;

  "requested_spec": "swig",
  "sha256": "ccd154dddec2b3b62528ca0e1aa395ae80aed2bbe17a156f7647f16756dbfffa",
  "size": 1331078,
  "subdir": "win-64",
  "timestamp": 1513182969953,
  "track_features": "",
  "url": "https://conda.anaconda.org/anaconda/win-64/**_swig-3.0.12-h047fa9f_3.tar.bz2_**",
  "version": "3.0.12"
}

  "requested_spec": "swig",
  "sha256": "ccd154dddec2b3b62528ca0e1aa395ae80aed2bbe17a156f7647f16756dbfffa",
  "size": 1331078,
  "subdir": "win-64",
  "timestamp": 1513182969953,
  "track_features": "",
  "url": "https://conda.anaconda.org/anaconda/win-64/**_swig-3.0.12-h5a33001_3.tar.bz2_**",
  "version": "3.0.12"
}

That should do it...

**Comment by PouyaT** [comment]
> 
> 
> Go to C:\Users\UserName\Anaconda3\envs\gym\conda-meta and open swig file. Change the the part of the url starts from swig-3.0.12-h047fa9f_3.tar.bz2 to swig-3.0.12-h5a33001_3.tar.bz2 ;
> 
> "requested_spec": "swig",
> "sha256": "ccd154dddec2b3b62528ca0e1aa395ae80aed2bbe17a156f7647f16756dbfffa",
> "size": 1331078,
> "subdir": "win-64",
> "timestamp": 1513182969953,
> "track_features": "",
> "url": "https://conda.anaconda.org/anaconda/win-64/swig-3.0.12-h047fa9f_3.tar.bz2",
> "version": "3.0.12"
> }
> 
> "requested_spec": "swig",
> "sha256": "ccd154dddec2b3b62528ca0e1aa395ae80aed2bbe17a156f7647f16756dbfffa",
> "size": 1331078,
> "subdir": "win-64",
> "timestamp": 1513182969953,
> "track_features": "",
> "url": "https://conda.anaconda.org/anaconda/win-64/swig-3.0.12-h5a33001_3.tar.bz2",
> "version": "3.0.12"
> }
> 
> That should do it...

what if you're not using anaconda?

**Comment by kemalaraz** [comment]
> > Go to C:\Users\UserName\Anaconda3\envs\gym\conda-meta and open swig file. Change the the part of the url starts from swig-3.0.12-h047fa9f_3.tar.bz2 to swig-3.0.12-h5a33001_3.tar.bz2 ;
> > "requested_spec": "swig",
> > "sha256": "ccd154dddec2b3b62528ca0e1aa395ae80aed2bbe17a156f7647f16756dbfffa",
> > "size": 1331078,
> > "subdir": "win-64",
> > "timestamp": 1513182969953,
> > "track_features": "",
> > "url": "https://conda.anaconda.org/anaconda/win-64/swig-3.0.12-h047fa9f_3.tar.bz2",
> > "version": "3.0.12"
> > }
> > "requested_spec": "swig",
> > "sha256": "ccd154dddec2b3b62528ca0e1aa395ae80aed2bbe17a156f7647f16756dbfffa",
> > "size": 1331078,
> > "subdir": "win-64",
> > "timestamp": 1513182969953,
> > "track_features": "",
> > "url": "https://conda.anaconda.org/anaconda/win-64/swig-3.0.12-h5a33001_3.tar.bz2",
> > "version": "3.0.12"
> > }
> > That should do it...
> 
> what if you're not using anaconda?

You can download the file from the url with h5a33... then extract it somewhere add its path to your PATH dierctory and then install swig and then try to install box2d again.

**Comment by PoojaKatariya1811** [comment]
I have the same problem, Tried changing swig-3.0.12-h047fa9f_3.tar.bz2 to swig-3.0.12-h5a33001_3.tar.bz2 and then tried to reinstall box2d. Still the same error

**Comment by super-pirata** [comment]
None of the solutions above solved my problem...
Windows 10 - 64
Python 3.7

**Comment by kne** [comment]
New builds that solve this issue will be available on the conda-forge channel with conda.

To install, use: `conda install -c conda-forge pybox2d`

**Comment by Sandy4321** [comment]
None of the solutions above solved my problem...
Windows 10 - 64
Python 3.7

**Comment by Sandy4321** [comment]
Box2D is installed 
E:\WINPYTHON_FULL_apr22\WPy64-3770\scripts>pip install Box2D
Collecting Box2D
  Downloading Box2D-2.3.10-cp37-cp37m-win_amd64.whl (1.3 MB)
     |████████████████████████████████| 1.3 MB 726 kB/s
Installing collected packages: Box2D
Successfully installed Box2D-2.3.10

**Comment by bring-nirachornkul** [comment]
> 

This solution solve my problem.
Python -- Version 3.10
Gym - 0.25.0
Anaconda 4.13.0
