### ISSUE TITLE
Problem with examples and Python 3.6

### ISSUE THREAD

**Issue by pgr123** [pybox2d/pybox2d#108]
Good morning,
I installed PyBox2D under Python 3.6 and it works fine with the examples in the directory examples/simple as you see : 

pascal@imedia-S2110:~/Bureau/pybox2d-master/examples/simple$ python3 simple_01.py
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Done!

pascal@imedia-S2110:~/Bureau/pybox2d-master/examples/simple$ python3 simple_02.py
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Done!

But when I try the examples in the directory examples (the example chain.py) I get an error : 

pascal@imedia-S2110:~/Bureau/pybox2d-master/examples$ python3 chain.py
Traceback (most recent call last):
  **File "chain.py", line 21, in <module>
    from .framework import (Framework, main)
ModuleNotFoundError: No module named '__main__.framework'; '__main__' is not a package**

Do you know what it means ? Can you help me ?
Thank you.
Have a good day.
Pascal Grandeau

**Comment by pgr123** [comment]
Also, the examples in testbed do not work with Python 3. Is it possible to make that test_Chain.py, for example, can be run with Python 3 ?

**Comment by pgr123** [comment]
Is PyBox2D definitely dead ??????
Nobody can help me ??????
is there anyone else at pyBox2D ?????

**Comment by pratikborhade1** [comment]
@pgr123 I am having the same problem. He had suggested to follow the exact setup steps in the previous posts by others but it isnt working either.

**Comment by pratikborhade1** [comment]
@pgr123 try removing the . in front of the ".framework"

**Comment by pgr123** [comment]
Thank you, you are right and with the new version of 2019-05-12, all seems to work.
