### ISSUE TITLE
SIGSEGV termination when using b2ContactListener

### ISSUE THREAD

**Issue by lewis-morris** [pybox2d/pybox2d#118]
I'm getting SIGSEGV terminations while b2ContactListener EndContact is called. It only happens when there is an excess of bodies in the world (hundreds). I appears it might be something to do with EndContact being called when the object is deleted as if I remove the step of removing bodies the crash doesn't happen.

Is there a way I can cancel the contact listener on a body before deletion? or any other ideas?

I'm using Ubuntu Linux and built pybox2d from the latest source.

**Comment by lewis-morris** [comment]
I think I've fixed this.

It appears I had multiple references to the bodies, one in the world object and some in my only custom class.

After calling world.DestroyBody I deleted them from my old list of bodies (with del) and also ran gc.collect for good measure.

No more errors so far.

**Comment by kne** [comment]
Multiple calls to `Destroy*` or lingering references to destroyed objects are probably the primary causes of crashes. Good to hear you resolved this on your own. Let me know if you run into anything else.

**Comment by lewis-morris** [comment]
Thanks for the reply and all the work you've put in. It's really fun to use.
