### ISSUE TITLE
fix printf compiler warnings due to Box2D_typemaps.i

### ISSUE THREAD

**Issue by kne** [pybox2d/pybox2d#58]
_From [Gustavo.Goretkin](https://code.google.com/u/100471049186360532270/) on January 14, 2015 22:27:34_

when compling pybox2d in Mac OS X 10.9 with clang, I get many, many warnings like

Box2D/Box2D_wrap.cpp:19157:92: warning: format specifies type 'int' but the
      argument has type 'Py_ssize_t' (aka 'long') [-Wformat]
  ...or list of length 2, got length &#37;d", PySequence_Size(swig_obj[1]));
                                     \~~   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                     &#37;ld

It looks like on gcc it's even worse because, I guess of in-lining, the error gets emitted from any function that accepts a b2Vec2.

I think the patch included, applied to /Box2D/Box2D_typemaps.i, should remove the warnings. The cast to (long) is because Py_ssize_t is "int", I think, on 32-bit platforms.

**Attachment:** [box2d_typemaps.patch](http://code.google.com/p/pybox2d/issues/detail?id=58)

_Original issue: http://code.google.com/p/pybox2d/issues/detail?id=58_

**Comment by goretkin** [comment]
Closed by https://github.com/pybox2d/pybox2d/commit/35f62682e46c5f1483e27cd23a7b0c63500e05dc
