### ISSUE TITLE
any plans for docs on the new testbed?

### ISSUE THREAD

**Issue by varoudis** [pybox2d/pybox2d#69]
Hi, I can't find the way to test the testbed from master.
Docs seem to be of a very old version.
Im using updated anaconda with extra pyjama installed. Latest MacOSX.
Thanks

**Comment by kne** [comment]
Hi @varoudis, 

Docs generally take very low priority over getting actual changes done, unfortunately. I'll at least update the wiki in a bit to reflect the new way of running the testbed. 

For now, see this PR for info on the changes: https://github.com/pybox2d/pybox2d/pull/62. You may very well run into issues with other backends as I haven't really been able to test all of them myself - be sure to let me know in that case.

**Comment by kne** [comment]
Should be fixed now - closing.
