### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by kne** [pybox2d/pybox2d#73]
Stop being lazy and just update it.

**Comment by kne** [comment]
`INSTALL` updated, API docs are still ancient

**Comment by ryukinix** [comment]
We can add too a INSTALL section for people whose like to use `pip`.

**Comment by pendragvn** [comment]
The line joint should be updated in the docs.  Took me forever to find that its actually called a wheel joint now.

**Comment by kne** [comment]
* No clue what my original intentions were with this issue 5 years later, but:

* Updated line joint -> wheel joint.
* Not supporting pip for now, unless someone wants to help with the CI for automatically building/pushing releases to PyPI.
* Releases will now be on conda-forge and this is reflected in the readme

Closing for now.
