### ISSUE TITLE
Running examples

### ISSUE THREAD

**Issue by Pastafarianist** [pybox2d/pybox2d#77]
```
~/pybox2d/examples $ python rope.py 
Traceback (most recent call last):
  File "rope.py", line 21, in <module>
    from .framework import (Framework, Keys, main)
SystemError: Parent module '' not loaded, cannot perform relative import
```

This is Python 3, but Python 2 fails with a similar error. How are examples supposed to be run?

**Comment by kne** [comment]
See https://github.com/pybox2d/pybox2d/blob/master/INSTALL.md#the-testbed-examples or https://github.com/pybox2d/pybox2d/wiki/manual#different-backends
