### ISSUE TITLE
liquidfun

### ISSUE THREAD

**Issue by DerThorsten** [pybox2d/pybox2d#78]
are there any plan to upgrade pybox2d to support liquidfun?

Greetings

**Comment by DerThorsten** [comment]
I started with that in my fork of liquidfun
https://github.com/DerThorsten/liquidfun

I just copied your *.i files.
The only problem I get, b2World complains about not having the "gravity" and "doSleep" kv.
Any ideas?

Greetings

**Comment by kne** [comment]
Hi @DerThorsten,

I wasn't even aware of the liquidfun project, to be honest. It does look interesting!

Unfortunately, it probably won't be as easy as you're hoping - it's not just a matter of copying `.i` files. I haven't looked into it extensively, but it seems like you'll have to wrap all of the new b2Particle* stuff and modify the current SWIG wrapper further to get access to the new features it brings.

**Comment by DerThorsten** [comment]
I want to approach this in little steps.
First step is build python bindings without the actual new particle system.
Once all tests run as in your bindings i will try to integrate the new particle system.

I am aware that a lot of b2Particle* things need to be wrapped, but so far I have troubles with
the keywords of the b2World  constructor.
Any idea why those could fail??
Except from them, it seems like the testsbed is still working (did not run all so far)

**Comment by kne** [comment]
I'm afraid that if you want to have any hope of success in wrapping the whole thing, you'll have to dig into the internals of how SWIG does things. There's a _lot_ of scary things in there.

**Comment by DerThorsten** [comment]
I am not scared by stuff like that, and I am willing to do the work.
But I am a bit puzzled why everything seems to work, just not the keywords.

So the thing is, I have a lot of experience with boost python (or pybind11).
If  I cannot do this with swig i will start over and rewrite complete fresh bindings with boost python or pybind11.
But I hope that I can build ontop of your excellent work!

**Comment by kne** [comment]
And as I've said - there are a lot of gory internals there. You gave me essentially no details of the error that you're receiving or anything that would aid in actual debugging such as version numbers. There are a bunch of settings related to kwargs, and a bunch of different idiosyncrasies relating to different SWIG versions. You claim to be willing to do the work, but are unwilling to look into why this isn't working - that part is puzzling to me.

If you want to rewrite the bindings (which is not a bad idea at all!), I wish you the best of luck. SWIG was unfortunately the best option in 2008 when I started this project.

**Comment by DerThorsten** [comment]
I just hoped there might be some "easy fix" as "just use this version".
Nevertheless thank you very much for your answers.

**Comment by mraxilus** [comment]
Liquid fun would be amazing actually.

**Comment by DerThorsten** [comment]
Hi, I found some time to work on my Liquidfun python bindings and it is almost usable (still very much to do) https://github.com/DerThorsten/liquidfun/tree/wip 
In the next weeks I might release some first version
