### ISSUE TITLE
ImportError: cannot import name 'b2World'

### ISSUE THREAD

**Issue by PaulJSchellenberg** [pybox2d/pybox2d#81]
when I try to run an example like how the Install.md tells me to

**python -m examples.pinball --backend=pygame**

I get a traceback to framework.py saying that

"...pybox2d/examples/framework.py", line 26, in <module>
    from Box2D import (b2World, b2AABB, b2CircleShape, b2Color, b2Vec2)
ImportError: cannot import name 'b2World'

**Comment by leeharr** [comment]
Which version of python?
Which version of pybox2d?
Where did you get it, or did you build it yourself?


What is the output for something like ...

$ python
>>> import Box2D
>>> Box2D.__version__
>>> dir(Box2D)

?

**Comment by PaulJSchellenberg** [comment]
Hi, Sorry for the late response.

I got it working. Turns out I skipped a vital step. I forgot to install the package into conda. *face palm*

Thanks for the help and sorry for the false alarm!
