### ISSUE TITLE
Please update the pypi package ("Unknown SWIG preprocessor directive" error)

### ISSUE THREAD

**Issue by TTimo** [pybox2d/pybox2d#82]
The 2.3b0 package that is on pypi will fail with the error reported in https://github.com/pybox2d/pybox2d/issues/76

Please consider updating the pypi version!

**Comment by jonasschneider** [comment]
Hi, we're looking to integrate some Box2D environments into the [OpenAI Gym](https://github.com/openai/gym), see https://github.com/openai/gym/pull/54. For installing pybox2d, we're running into the same SWIG errors.

For now, I've repackaged the master version as https://pypi.python.org/pypi/box2d-py -- very suboptimal and I'd like to get rid of this package as soon as possible. This is not intended as a fork. @kne, once you bump the `Box2D` pypi package, please ping me and I will nuke box2d-py.

**Comment by jietang** [comment]
Any updates here?

**Comment by zommerfelds** [comment]
+1

**Comment by Majki** [comment]
+1

**Comment by manuq** [comment]
+1

**Comment by kne** [comment]
Updated on pypi https://pypi.python.org/pypi/Box2D/2.3.2

Apologies for the egregious delay. Was hoping to move toward the [Cython rewrite](https://github.com/pybox2d/cython_test) by this point to rid myself of supporting the awfulness that is SWIG, but haven't had nearly enough time. Thanks for providing the alternative, @jonasschneider.
