### ISSUE TITLE
ImportError: No module named Box2D (I cloned and built the source)

### ISSUE THREAD

**Issue by dongleecsu** [pybox2d/pybox2d#85]
Hi, I tried to install pybox2d on my PC (OS: Ubuntu 14.04 LTS 64bit). But I got the error: **ImportError: No module named Box2D.**
I followed the instruction from here [https://github.com/pybox2d/pybox2d/blob/master/INSTALL.md#building-from-source-linux](url)
This is what I did:
1. `sudo apt-get install build-essential python-dev swig python-pygame git`
2. `git clone https://github.com/pybox2d/pybox2d`
3. `python setup.py build`
    `sudo python setup.py install`
And everything went well, so I ran the following command in a python shell:
`import Box2D`
The following error threw:

> > > import Box2D
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > ImportError: No module named Box2D

Could you please give me any idea about this? Thank you.

Dong Li

**Comment by kne** [comment]
I believe the current master should be better about building right after cloning. Feel free to re-open if you still care/still have the issue.
