### ISSUE TITLE
Windows 64 - Python 3.5 Prebuild not found

### ISSUE THREAD

**Issue by guidefreitas** [pybox2d/pybox2d#89]
Hi, could you please compile and make win64 python 3.5 build available at kne anaconda channel?

**Comment by ViktorM** [comment]
The same request. Thanks!

**Comment by ViktorM** [comment]
It is needed very much to get some gym environments running on Windows.

**Comment by kne** [comment]
New builds are on conda-forge. To install, use: `conda install -c conda-forge pybox2d`
