### ISSUE TITLE
AttributeError: 'module' object has no attribute 'RAND_LIMIT_swigconstant'

### ISSUE THREAD

**Issue by JoanSymbio** [pybox2d/pybox2d#95]
Right after installation:
```
>>> import Box2D as b2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/joanaguilar/.local/lib/python2.7/site-packages/Box2D/__init__.py", line 20, in <module>
    from .Box2D import *
  File "/home/joanaguilar/.local/lib/python2.7/site-packages/Box2D/Box2D.py", line 435, in <module>
    _Box2D.RAND_LIMIT_swigconstant(_Box2D)
AttributeError: 'module' object has no attribute 'RAND_LIMIT_swigconstant'
```

Using Ubuntu 14.04 with PyBox2D installed via pip.

**Comment by Perseus101** [comment]
I am having the same error with PyBox2D installed via building from source. (Ubuntu 16.04)

**Comment by StrangeTcy** [comment]
I'm having a similar issue, only there's no `_swigconstant` in it, just `AttributeError: 'module' object has no attribute 'RAND_LIMIT'`

**Comment by LLionel** [comment]
I'm having a similar issue on Ubuntu 16.04, only there's no _swigconstant in it, just AttributeError: 'module' object has no attribute 'RAND_LIMIT'

**Comment by TTimo** [comment]
On Windows as well (Python 2.7 win32), all packages latest:

```
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    from Box2D import __version__ as Box2DVersion
  File "C:\Python27\lib\site-packages\Box2D\__init__.py", line 20, in <module>
    from .Box2D import *
  File "C:\Python27\lib\site-packages\Box2D\Box2D.py", line 435, in <module>
    _Box2D.RAND_LIMIT_swigconstant(_Box2D)
AttributeError: 'module' object has no attribute 'RAND_LIMIT_swigconstant'
```

**Comment by TTimo** [comment]
Installing via pip.exe results in the problem above, but doing a git clone of the repository and building manually does not .. so maybe a fix was made in git but never propagated to whatever pypi distributes?

**Comment by kne** [comment]
New builds that solve this issue will be available on the conda-forge channel with conda.

To install, use: `conda install -c conda-forge pybox2d`

**Comment by JoanSymbio** [comment]
:+1:

Thanks for the update!

**Comment by Python-Ninja-Hebi** [comment]
When will change pip?

**Comment by TTimo** [comment]
https://pypi.org/project/Box2D/#files pypi claims 2.3.10 but if you're not in one of those prebuilt distributions it looks like it'll still grab and build 2.3.2, that seems wrong.
