### ISSUE TITLE
Running examples: 'cannot perform relative import'

### ISSUE THREAD

**Issue by tensor8** [pybox2d/pybox2d#97]
Install on OS X, python3.4 as described in install guide.

I try to run car.py:

```python
>> python examples/car.py --backend=pygame
Traceback (most recent call last):
  File "examples/body_types.py", line 21, in <module>
    from .framework import (Framework, Keys, main)
SystemError: Parent module '' not loaded, cannot perform relative import
```

**Comment by AndreasGerken** [comment]
Hi, I have the same Issue
From looking at the open Issues it looks like the project might not be maintained anymore

**Comment by kne** [comment]
See: https://github.com/pybox2d/pybox2d/blob/master/INSTALL.md
See: https://github.com/pybox2d/pybox2d/wiki/manual#different-backends

In short:
`$ python -m examples.web --backend=pygame`

**Comment by TamedTornado** [comment]
Following your instructions, this doesn't work. Pygame is installed, but same error.
